"""Own signal-processing building blocks: STFT, CQT, mel, onset, HPSS (L1)."""

from .audio import DEFAULT_SR, load_audio, resample, to_mono
from .cqt import C1_HZ, CQTKernel, chroma_cqt, chroma_matrix, cqt, cqt_frequencies, cqt_kernel
from .mel import hz_to_mel, log_filterbank, mel_filterbank, mel_frequencies, mel_spectrogram, mel_to_hz
from .onset import (
    ONSET_PRESETS,
    OnsetConfig,
    band_spectrogram,
    detect_onsets,
    envelope_from_bands,
    onset_config,
    onset_envelope,
    peak_pick,
    pick_onsets,
)
from .spectral import (
    amplitude_to_db,
    fft_frequencies,
    frames_to_time,
    hz_to_midi,
    istft,
    midi_to_hz,
    n_frames,
    power_to_db,
    stft,
    time_to_frames,
    window,
)

__all__ = [
    "C1_HZ",
    "CQTKernel",
    "DEFAULT_SR",
    "ONSET_PRESETS",
    "OnsetConfig",
    "amplitude_to_db",
    "band_spectrogram",
    "chroma_cqt",
    "chroma_matrix",
    "cqt",
    "cqt_frequencies",
    "cqt_kernel",
    "detect_onsets",
    "envelope_from_bands",
    "fft_frequencies",
    "frames_to_time",
    "hz_to_mel",
    "hz_to_midi",
    "istft",
    "load_audio",
    "log_filterbank",
    "mel_filterbank",
    "mel_frequencies",
    "mel_spectrogram",
    "mel_to_hz",
    "midi_to_hz",
    "n_frames",
    "onset_config",
    "onset_envelope",
    "peak_pick",
    "pick_onsets",
    "power_to_db",
    "resample",
    "stft",
    "time_to_frames",
    "to_mono",
    "window",
]
